# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=50)),
                ('name_text', models.CharField(max_length=50)),
                ('brand_text', models.CharField(max_length=50)),
                ('number_stock', models.CharField(max_length=50)),
                ('number_reserve', models.CharField(max_length=50)),
                ('price_float', models.FloatField()),
                ('price_discount', models.FloatField()),
                ('note_text', models.CharField(max_length=50)),
            ],
        ),
    ]
